// <auto-generated />
using System;
using EcoCycleCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoCycleCore.Migrations
{
    [DbContext(typeof(EcoCycleContext))]
    [Migration("20260714032737_AgregarDocumentoIdentidad")]
    partial class AgregarDocumentoIdentidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcoCycleCore.Models.Canje", b =>
                {
                    b.Property<int>("CanjeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("canje_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CanjeId"));

                    b.Property<string>("CodigoDigital")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigo_digital");

                    b.Property<int>("CuponId")
                        .HasColumnType("int")
                        .HasColumnName("cupon_id");

                    b.Property<DateTime?>("FechaCanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_canje")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("CanjeId");

                    b.HasIndex("CuponId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex(new[] { "CodigoDigital" }, "UQ__CANJES__ECD7D41A82363E0E")
                        .IsUnique();

                    b.ToTable("CANJES", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Cupone", b =>
                {
                    b.Property<int>("CuponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cupon_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CuponId"));

                    b.Property<int>("CostPuntos")
                        .HasColumnType("int")
                        .HasColumnName("cost_puntos");

                    b.Property<string>("DescBeneficio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("desc_beneficio");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.Property<string>("TiendaNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("tienda_nombre");

                    b.HasKey("CuponId");

                    b.ToTable("CUPONES", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Entrega", b =>
                {
                    b.Property<int>("EntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entrega_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregaId"));

                    b.Property<int>("CentroId")
                        .HasColumnType("int")
                        .HasColumnName("centro_id");

                    b.Property<int>("CiudadanoId")
                        .HasColumnType("int")
                        .HasColumnName("ciudadano_id");

                    b.Property<DateTime?>("FechaEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_entrega")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PesoReal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("peso_real");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int")
                        .HasColumnName("publicacion_id");

                    b.Property<int>("PuntosOtorgados")
                        .HasColumnType("int")
                        .HasColumnName("puntos_otorgados");

                    b.HasKey("EntregaId");

                    b.HasIndex("CiudadanoId");

                    b.HasIndex("PublicacionId");

                    b.ToTable("ENTREGAS", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Materiale", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<string>("NombreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_material");

                    b.Property<decimal>("PuntosPorKilo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("puntos_por_kilo");

                    b.HasKey("MaterialId");

                    b.ToTable("MATERIALES", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Publicacione", b =>
                {
                    b.Property<int>("PublicacionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("publicaciones_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicacionesId"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.Property<decimal>("PesoCantidad")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("peso_cantidad");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ubicacion");

                    b.Property<string>("UrlImagen")
                        .HasMaxLength(2083)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2083)")
                        .HasColumnName("url_imagen");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("PublicacionesId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PUBLICACIONES", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("DocumentoIdentidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PuntosAcumulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("puntos_acumulacion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("UsuarioId");

                    b.HasIndex(new[] { "Correo" }, "UQ__USUARIOS__2A586E0B3A764D46")
                        .IsUnique();

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("EcoCycleCore.Models.Canje", b =>
                {
                    b.HasOne("EcoCycleCore.Models.Cupone", "Cupon")
                        .WithMany("Canjes")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CANJES_CUPONES");

                    b.HasOne("EcoCycleCore.Models.Usuario", "Usuario")
                        .WithMany("Canjes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CANJES_USUARIOS");

                    b.Navigation("Cupon");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Entrega", b =>
                {
                    b.HasOne("EcoCycleCore.Models.Usuario", "Ciudadano")
                        .WithMany("Entregas")
                        .HasForeignKey("CiudadanoId")
                        .IsRequired()
                        .HasConstraintName("FK_ENTREGAS_USUARIOS");

                    b.HasOne("EcoCycleCore.Models.Publicacione", "Publicacion")
                        .WithMany("Entregas")
                        .HasForeignKey("PublicacionId")
                        .IsRequired()
                        .HasConstraintName("FK_ENTREGAS_PUBLICACIONES");

                    b.Navigation("Ciudadano");

                    b.Navigation("Publicacion");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Publicacione", b =>
                {
                    b.HasOne("EcoCycleCore.Models.Materiale", "Material")
                        .WithMany("Publicaciones")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PUBLICACIONES_MATERIALES");

                    b.HasOne("EcoCycleCore.Models.Usuario", "Usuario")
                        .WithMany("Publicaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PUBLICACIONES_USUARIOS");

                    b.Navigation("Material");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Cupone", b =>
                {
                    b.Navigation("Canjes");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Materiale", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Publicacione", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("EcoCycleCore.Models.Usuario", b =>
                {
                    b.Navigation("Canjes");

                    b.Navigation("Entregas");

                    b.Navigation("Publicaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
